### PR TITLE
teeny framework, teeny pull-request

### PR DESCRIPTION
**Pull request by alex-cova**
Added a teeny json serializer (no dependencies) & a teeny framework that has a cool name to configure endpoints easy :)

### CODE REVIEW

**Comment by JonathanGiles** [comment]
Thanks for your contribution! I have been working on a bit of a overhaul to introduce server-sent event support, which I'll be pushing soon. Unfortunately that may introduce some work for you to integrate - sorry about that! I will review and get some feedback to you on this ASAP - it looks very interesting.

**Comment by JonathanGiles** [comment]
Code has been pushed - sorry for the collision. Please do update, and then lets chat about your PR!

**Comment by alex-cova** [comment]
> Thanks for your contribution! I have been working on a bit of a overhaul to introduce server-sent event support, which I'll be pushing soon. Unfortunately that may introduce some work for you to integrate - sorry about that! I will review and get some feedback to you on this ASAP - it looks very interesting.

No worries, looking forward to contribute even more, and better. btw would be great if java 21 is used instead of 9, I'm open to any suggestion 😃

**Comment by JonathanGiles** [comment]
Given that this is a fun play project, I think it is reasonable to increase the baseline.... But I still like the thought of playing nicely with earlier Java versions. Maybe a baseline of 17 might do?

**Comment by alex-cova** [comment]
A baseline of 17 is good enough

**Comment by JonathanGiles** [comment]
I'll make that change sometime soon. After we get your pr merged

**Comment by JonathanGiles** [comment]
You're going to open a new pr I'm guessing?

**Pull request closed without merging**
